export const styles = {
  labelInput: {
    fontSize: "0.75rem",
    fontWeight: "bold",
    color: "#4A148C",
    marginLeft: "5px",
  },
  inputGroup: { display: "flex", flexDirection: "column", gap: "5px" },
  btnGroup: { display: "flex", gap: "10px", height: "45px" },
  statsRow: { display: "flex", gap: "20px", marginBottom: "25px" },
  miniCard: {
    flex: 1,
    backgroundColor: "#FFF",
    padding: "20px",
    borderRadius: "15px",
    border: "1px solid #E0E5F2",
    textAlign: "center",
  },
  statNumber: {
    fontSize: "1.5rem",
    fontWeight: "800",
    color: "#4A148C",
    margin: 0,
  },
  labelFaint: { color: "#A3AED0", fontSize: "0.8rem", fontWeight: "bold" },
  card: {
    backgroundColor: "#FFF",
    padding: "25px",
    borderRadius: "15px",
    boxShadow: "0 10px 20px rgba(0,0,0,0.02)",
    marginBottom: "30px",
  },
  cardTitle: {
    color: "#4A148C",
    margin: 0,
    fontSize: "1.1rem",
    fontWeight: "700",
    marginBottom: "20px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1.5fr 1.5fr 1fr 1fr",
    gap: "15px",
    alignItems: "end",
  },
  formGridEndereco: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr 0.5fr 1.5fr",
    gap: "15px",
    marginTop: "15px",
  },
  input: {
    padding: "12px",
    borderRadius: "10px",
    border: "1px solid #E0E5F2",
    outline: "none",
    backgroundColor: "#F4F7FE",
    fontSize: "0.9rem",
    transition: "0.3s",
  },
  inputBusca: {
    padding: "10px 20px",
    borderRadius: "25px",
    border: "1px solid #E0E5F2",
    backgroundColor: "#F4F7FE",
    width: "250px",
    outline: "none",
  },
  btnPrimary: {
    backgroundColor: "#4A148C",
    color: "#FFF",
    border: "none",
    padding: "12px 20px",
    borderRadius: "10px",
    fontWeight: "bold",
    cursor: "pointer",
    width: "100%",
  },
  btnCancel: {
    backgroundColor: "#EEE",
    color: "#666",
    border: "none",
    padding: "12px 20px",
    borderRadius: "10px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  btnEdit: {
    backgroundColor: "#E3F2FD",
    color: "#1976D2",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    marginRight: "8px",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  btnDelete: {
    backgroundColor: "#FFE5EC",
    color: "#D32F2F",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  btnSuccess: {
    backgroundColor: "#E8F5E9",
    color: "#2E7D32",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  headerAcoes: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "15px",
    color: "#A3AED0",
    fontSize: "0.8rem",
    textTransform: "uppercase",
  },
  td: { padding: "15px", color: "#2B3674", borderBottom: "1px solid #F4F7FE" },
  btnToggle: {
    padding: "8px 20px",
    borderRadius: "20px",
    border: "none",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.8rem",
  },
  checkboxGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: "10px",
    marginTop: "10px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "#FFF",
    padding: "25px",
    borderRadius: "15px",
    width: "400px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
  },
};
